version: '3.8'

services:
  lambda-test:
    image: node:20-alpine
    container_name: eventbridge-router-lambda
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: tail -f /dev/null
